// The .cpp file for this header is generated by a Bazel's genrule that will
// fill the array with the contents of the haarcascade_frontalface_default.xml
// file.
#pragma once

#include <cstddef>

namespace cake::data {
extern const unsigned char kHaarCascadeData[];
extern const std::size_t kHaarCascadeDataSize;
} // namespace cake::data
